# Generated by Django 6.0.6 on 2026-06-24 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskcomment_taskfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Задача создана'), ('updated', 'Задача изменена'), ('status_changed', 'Изменён статус'), ('assigned', 'Назначен исполнитель'), ('unassigned', 'Снят исполнитель'), ('commented', 'Добавлен комментарий'), ('file_uploaded', 'Загружен файл'), ('completed', 'Задача выполнена'), ('archived', 'Задача перенесена в архив')], max_length=30, verbose_name='Тип события')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_history_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие задачи',
                'verbose_name_plural': 'История задач',
                'ordering': ['-created_at'],
            },
        ),
    ]
