# Generated by Django 6.0.6 on 2026-06-26 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assignment_type',
            field=models.CharField(choices=[('assignee', 'Assignee'), ('watcher', 'Watcher')], default='assignee', max_length=20, verbose_name='Assignment type'),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'user', 'assignment_type')},
        ),
    ]
