# Generated by Codex for chat attachments MVP.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_taskassignment_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskfile",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="tasks.taskcomment",
                verbose_name="Comment",
            ),
        ),
    ]
