# Generated by Django 6.0.6 on 2026-06-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(default='temp', max_length=100, unique=True, verbose_name='Код'),
            preserve_default=False,
        ),
    ]
